# Generated by Django 2.2.4 on 2019-10-18 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_marketingmessage_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketingmessage',
            old_name='acitve',
            new_name='active',
        ),
    ]
