# Generated by Django 2.2.4 on 2019-10-20 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_auto_20191019_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sliders',
            options={'ordering': ['order']},
        ),
    ]
