# Generated by Django 2.2.4 on 2020-08-15 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userdefaultaddress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useradress',
            options={'ordering': ['-timestamp', '-updated']},
        ),
    ]
