# Generated by Django 2.2.4 on 2019-08-31 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.DecimalField(decimal_places=6, max_digits=10000000),
        ),
    ]
