# Generated by Django 2.2.4 on 2019-08-31 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20190831_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10000000, null=True),
        ),
    ]
