# Generated by Django 2.1 on 2019-09-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_variations_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='variations',
            name='categoes',
            field=models.CharField(choices=[('size', 'size'), ('color', 'color'), ('package', 'package')], default='size', max_length=120),
        ),
    ]
