# Generated by Django 2.1 on 2019-09-03 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_variations_categoes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variations',
            old_name='categoes',
            new_name='category',
        ),
    ]
