# Generated by Django 2.1 on 2019-09-03 18:16

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20190903_2255'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='variations',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
